from . import sale_order
from . import crm_lead
from . import product
from . import stock_picking
from . import sale_order_line
from . import purchase_order
from . import purchase_order_line
from . import task
from . import marge_sales_orders
